"""Initial schema with all models

Revision ID: 540d8be25367
Revises: 
Create Date: 2026-01-24 06:25:55.867826

"""
from alembic import op
import sqlalchemy as sa
from app.models.base import GUID, JSON


# revision identifiers, used by Alembic.
revision = '540d8be25367'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_sponsor', sa.String(length=255), nullable=False),
    sa.Column('program_manager', sa.String(length=255), nullable=False),
    sa.Column('technical_lead', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('start_date < end_date', name='check_program_dates'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_index(op.f('ix_programs_name'), 'programs', ['name'], unique=False)
    op.create_table('resources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('LABOR', 'NON_LABOR', name='resourcetype'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_name'), 'resources', ['name'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('worker_types',
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_types_id'), 'worker_types', ['id'], unique=False)
    op.create_index(op.f('ix_worker_types_type'), 'worker_types', ['type'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', GUID(), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('before_values', JSON(), nullable=True),
    sa.Column('after_values', JSON(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_operation'), 'audit_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('program_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_sponsor', sa.String(length=255), nullable=False),
    sa.Column('project_manager', sa.String(length=255), nullable=False),
    sa.Column('technical_lead', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('cost_center_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('start_date < end_date', name='check_project_dates'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_cost_center_code'), 'projects', ['cost_center_code'], unique=True)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_program_id'), 'projects', ['program_id'], unique=False)
    op.create_table('rates',
    sa.Column('worker_type_id', GUID(), nullable=False),
    sa.Column('rate_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date < end_date', name='check_rate_dates'),
    sa.CheckConstraint('rate_amount > 0', name='check_rate_positive'),
    sa.ForeignKeyConstraint(['worker_type_id'], ['worker_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_end_date'), 'rates', ['end_date'], unique=False)
    op.create_index(op.f('ix_rates_id'), 'rates', ['id'], unique=False)
    op.create_index(op.f('ix_rates_start_date'), 'rates', ['start_date'], unique=False)
    op.create_index(op.f('ix_rates_worker_type_id'), 'rates', ['worker_type_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('role_type', sa.Enum('ADMIN', 'PROGRAM_MANAGER', 'PROJECT_MANAGER', 'FINANCE_MANAGER', 'RESOURCE_MANAGER', 'VIEWER', name='roletype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_type'), 'user_roles', ['role_type'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('workers',
    sa.Column('worker_type_id', GUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_type_id'], ['worker_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_external_id'), 'workers', ['external_id'], unique=True)
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_index(op.f('ix_workers_name'), 'workers', ['name'], unique=False)
    op.create_index(op.f('ix_workers_worker_type_id'), 'workers', ['worker_type_id'], unique=False)
    op.create_table('project_phases',
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('phase_type', sa.Enum('PLANNING', 'EXECUTION', name='phasetype'), nullable=False),
    sa.Column('capital_budget', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('expense_budget', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('capital_budget + expense_budget = total_budget', name='check_budget_sum'),
    sa.CheckConstraint('capital_budget >= 0', name='check_capital_budget_positive'),
    sa.CheckConstraint('expense_budget >= 0', name='check_expense_budget_positive'),
    sa.CheckConstraint('total_budget >= 0', name='check_total_budget_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_phases_id'), 'project_phases', ['id'], unique=False)
    op.create_index(op.f('ix_project_phases_project_id'), 'project_phases', ['project_id'], unique=False)
    op.create_table('scope_assignments',
    sa.Column('user_role_id', GUID(), nullable=False),
    sa.Column('program_id', GUID(), nullable=True),
    sa.Column('project_id', GUID(), nullable=True),
    sa.Column('scope_type', sa.Enum('GLOBAL', 'PROGRAM', 'PROJECT', name='scopetype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_assignments_id'), 'scope_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_scope_assignments_program_id'), 'scope_assignments', ['program_id'], unique=False)
    op.create_index(op.f('ix_scope_assignments_project_id'), 'scope_assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_scope_assignments_scope_type'), 'scope_assignments', ['scope_type'], unique=False)
    op.create_index(op.f('ix_scope_assignments_user_role_id'), 'scope_assignments', ['user_role_id'], unique=False)
    op.create_table('resource_assignments',
    sa.Column('resource_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('project_phase_id', GUID(), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('allocation_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('capital_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expense_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('allocation_percentage >= 0 AND allocation_percentage <= 100', name='check_allocation_percentage'),
    sa.CheckConstraint('capital_percentage + expense_percentage = 100', name='check_accounting_split'),
    sa.CheckConstraint('capital_percentage >= 0 AND capital_percentage <= 100', name='check_capital_percentage'),
    sa.CheckConstraint('expense_percentage >= 0 AND expense_percentage <= 100', name='check_expense_percentage'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_phase_id'], ['project_phases.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_assignments_assignment_date'), 'resource_assignments', ['assignment_date'], unique=False)
    op.create_index(op.f('ix_resource_assignments_id'), 'resource_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_resource_assignments_project_id'), 'resource_assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_resource_assignments_project_phase_id'), 'resource_assignments', ['project_phase_id'], unique=False)
    op.create_index(op.f('ix_resource_assignments_resource_id'), 'resource_assignments', ['resource_id'], unique=False)
    op.create_table('actuals',
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('resource_assignment_id', GUID(), nullable=True),
    sa.Column('external_worker_id', sa.String(length=100), nullable=False),
    sa.Column('worker_name', sa.String(length=255), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=False),
    sa.Column('allocation_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('capital_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('expense_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('actual_cost >= 0', name='check_actual_cost_positive'),
    sa.CheckConstraint('allocation_percentage >= 0 AND allocation_percentage <= 100', name='check_actual_allocation_percentage'),
    sa.CheckConstraint('capital_amount + expense_amount = actual_cost', name='check_actual_cost_split'),
    sa.CheckConstraint('capital_amount >= 0', name='check_capital_amount_positive'),
    sa.CheckConstraint('expense_amount >= 0', name='check_expense_amount_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resource_assignment_id'], ['resource_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actuals_actual_date'), 'actuals', ['actual_date'], unique=False)
    op.create_index(op.f('ix_actuals_external_worker_id'), 'actuals', ['external_worker_id'], unique=False)
    op.create_index(op.f('ix_actuals_id'), 'actuals', ['id'], unique=False)
    op.create_index(op.f('ix_actuals_project_id'), 'actuals', ['project_id'], unique=False)
    op.create_index(op.f('ix_actuals_resource_assignment_id'), 'actuals', ['resource_assignment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actuals_resource_assignment_id'), table_name='actuals')
    op.drop_index(op.f('ix_actuals_project_id'), table_name='actuals')
    op.drop_index(op.f('ix_actuals_id'), table_name='actuals')
    op.drop_index(op.f('ix_actuals_external_worker_id'), table_name='actuals')
    op.drop_index(op.f('ix_actuals_actual_date'), table_name='actuals')
    op.drop_table('actuals')
    op.drop_index(op.f('ix_resource_assignments_resource_id'), table_name='resource_assignments')
    op.drop_index(op.f('ix_resource_assignments_project_phase_id'), table_name='resource_assignments')
    op.drop_index(op.f('ix_resource_assignments_project_id'), table_name='resource_assignments')
    op.drop_index(op.f('ix_resource_assignments_id'), table_name='resource_assignments')
    op.drop_index(op.f('ix_resource_assignments_assignment_date'), table_name='resource_assignments')
    op.drop_table('resource_assignments')
    op.drop_index(op.f('ix_scope_assignments_user_role_id'), table_name='scope_assignments')
    op.drop_index(op.f('ix_scope_assignments_scope_type'), table_name='scope_assignments')
    op.drop_index(op.f('ix_scope_assignments_project_id'), table_name='scope_assignments')
    op.drop_index(op.f('ix_scope_assignments_program_id'), table_name='scope_assignments')
    op.drop_index(op.f('ix_scope_assignments_id'), table_name='scope_assignments')
    op.drop_table('scope_assignments')
    op.drop_index(op.f('ix_project_phases_project_id'), table_name='project_phases')
    op.drop_index(op.f('ix_project_phases_id'), table_name='project_phases')
    op.drop_table('project_phases')
    op.drop_index(op.f('ix_workers_worker_type_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_name'), table_name='workers')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_external_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_type'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_rates_worker_type_id'), table_name='rates')
    op.drop_index(op.f('ix_rates_start_date'), table_name='rates')
    op.drop_index(op.f('ix_rates_id'), table_name='rates')
    op.drop_index(op.f('ix_rates_end_date'), table_name='rates')
    op.drop_table('rates')
    op.drop_index(op.f('ix_projects_program_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_cost_center_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_operation'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_worker_types_type'), table_name='worker_types')
    op.drop_index(op.f('ix_worker_types_id'), table_name='worker_types')
    op.drop_table('worker_types')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_name'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_programs_name'), table_name='programs')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###